version: 2
jobs:
  build_project:
    machine: true
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack-work-{{ checksum "stack.yaml" }}-{{ checksum "HaskellTestApp.cabal" }}
      - run: .circleci/setup_heroku.sh
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker build -t registry.heroku.com/$HEROKU_APP/web:$CIRCLE_BRANCH .
      - run: docker push registry.heroku.com/$HEROKU_APP/web:$CIRCLE_BRANCH
      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}-{{ checksum "HaskellTestApp.cabal" }}
          paths:
            - ".stack-work"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_project
